import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";


const font = Nunito_Sans({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} min-h-screen flex flex-col antialiased`}
      >
        <div className="flex-1 w-full h-full">
            {children}
        </div>
      </body>
    </html>
  );
}
